### ISSUE TITLE
Windows: bsddb error in rdflib

### ISSUE THREAD

**Issue by ikarth** [c-w/Gutenberg#26]
The library installs and ```text = strip_headers(load_etext(2701)).strip()``` works fine.

But when I run:

    from gutenberg.query import get_metadata
    print(get_metadata("title", 2701))

I get:

    Traceback (most recent call last):
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\gutenberg\query\api.py", line 101, in _metadata
        return cls.__metadata
    AttributeError: type object 'TitleExtractor' has no attribute '_MetadataExtractor__metadata'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\gutenberg\query\api.py", line 34, in get_metadata
        metadata_values = MetadataExtractor.get(feature_name).get_metadata(etextno)
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\gutenberg\query\extractors.py", line 30, in get_metadata
        query = cls._metadata()[etext:cls.predicate():]
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\gutenberg\query\api.py", line 103, in _metadata
        cls.__metadata = load_metadata()
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\gutenberg\acquire\metadata.py", line 130, in load_metadata
        return _open_or_create_metadata_graph()
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\gutenberg\acquire\metadata.py", line 108, in _open_or_create_metadata_graph
        _METADATA_DATABASE_SINGLETON = _create_metadata_graph()
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\gutenberg\acquire\metadata.py", line 91, in _create_metadata_graph
        return Graph(store=store, identifier='urn:gutenberg:metadata')
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\rdflib\graph.py", line 312, in __init__
        self.__store = store = plugin.get(store, Store)()
      File "F:\Isaac\Dev\nanogenmo2015\pyenv\lib\site-packages\rdflib\plugins\sleepycat.py", line 52, in __init__
        "Unable to import bsddb/bsddb3, store is unusable.")
    ImportError: Unable to import bsddb/bsddb3, store is unusable.

Near as I can tell, it seems to be an error with RDFlib relying on bsddb3, and bsddb3 not maintaining their Windows package properly. 

Trying to install bsddb3 directly with ```pip install bsddb3``` gets me:

    Collecting bsddb3
      Using cached bsddb3-6.1.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\Users\User\AppData\Local\Temp\pip-build-uvi4bvaa\bsddb3\setup.py", line 42, in <module>
            import setup3
          File "C:\Users\User\AppData\Local\Temp\pip-build-uvi4bvaa\bsddb3\setup3.py", line 375, in <module>
            with open(os.path.join(incdir, 'db.h'), 'r') as f :
        FileNotFoundError: [Errno 2] No such file or directory: 'db/include\\db.h'
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-build-uvi4bvaa\bsddb3

I'm using Windows 7 and Python 3.4 x64.

Is there any easy way to switch the backend [persistence store](https://github.com/RDFLib/rdflib/blob/master/docs/persistence.rst) to, say, [RDFLib-SQLAlchemy](https://github.com/RDFLib/rdflib-sqlalchemy)?

**Comment by c-w** [comment]
Hi Isaac. Thanks for getting in touch.

I haven't tested the package on Windows and I haven't deeply investigated using an alternative persistence store for RDFlib (pull requests welcome on both accounts).

However, if you are willing to down-grade to Python 2.7, there's a really simple fix for your issue: just remove the external bsddb3 dependency (Sleepycat is part of the standard library in Python 2).

**Comment by yever** [comment]
On Ubuntu 14.04 I got the same error with pip and had to do:
```sh
$ BERKELEYDB_DIR=/usr pip install -r requirements.pip
```

**Comment by c-w** [comment]
@yever: I updated the installation section in the ReadMe to reflect the required BSD-DB setup steps.

**Comment by yever** [comment]
Thank you. 
But this is a very ubuntu-centric solution. The issue here is about Windows. Are there instructions for other operating systems? I had to dig quite a bit to find the one for Ubuntu.

**Comment by c-w** [comment]
@yever: Unfortunately I don't have access to a Windows development machine so I can't help here.

Given the pain related to Python3 and BSD-DB, I think it's now worth to investigate switching the RDFlib backing store.

Resolving in favor of #31.

**Comment by michaelklachko** [comment]
I also had the issue with bsddb requirement preventing gutenberg install on Windows. I found a simple fix:
http://stackoverflow.com/questions/33714698/installing-bsddb3-6-1-1-in-windows-filenotfounderror-db-include-db-h

**Comment by anjabeth** [comment]
I'm having the same issue getting Gutenberg to install on Windows 64, and the stackoverflow fix looks promising, but the whl file it says to download is no longer there, and I'm pretty new to this so not sure which one I should download. My options seem to be "bsddb3-6.2.1-cp27-cp27m-win_amd64.whl", "bsddb3-6.2.1-cp34-cp34m-win_amd64.whl", "bsddb3-6.2.1-cp35-cp35m-win_amd64.whl", and "bsddb3-6.2.1-cp36-cp36m-win_amd64.whl", but I don't know what the difference between the cp parts are. Advice?

**Comment by ikarth** [comment]
I believe that the cp parts correspond to CPython versions.

**Comment by hugovk** [comment]
That's right, cp27 is for CPython 2.7. There's 32-bit and 64-bit versions:

 * bsddb3-6.2.1-cp27-cp27m-win32.whl
 * bsddb3-6.2.1-cp27-cp27m-win_amd64.whl

http://www.lfd.uci.edu/~gohlke/pythonlibs/#bsddb3
