### ISSUE TITLE
MemoryError: (12, 'Not enough space -- unable to allocate memory for mutex; resize mutex region')

### ISSUE THREAD

**Issue by hugovk** [c-w/Gutenberg#28]
I'm getting a `MemoryError` when using `get_metadata`. It was working for me earlier. I have about 7.5GB free on C:\ and 53GB free on E:\, and 4GB free RAM.

```python
C:\stufftodelete>pip freeze | grep Gutenberg
Gutenberg==0.4.0

C:\stufftodelete>python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gutenberg.acquire import load_etext
INFO:rdflib:RDFLib Version: 4.2.1
>>> from gutenberg.cleanup import strip_headers
>>> text = strip_headers(load_etext(2701)).strip()
>>> len(text)
1237486
>>> text[:100]
u"MOBY DICK; OR THE WHALE\r\n\r\nBy Herman Melville\r\n\r\n\r\n\r\n\r\nOriginal Transcriber's Notes:\r\n\r\nThis text is
"
>>> 
>>> from gutenberg.query import get_etexts
>>> from gutenberg.query import get_metadata
>>> 
>>> get_metadata('title', 2701)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\gutenberg\query\api.py", line 34, in get_metadata
    metadata_values = MetadataExtractor.get(feature_name).get_metadata(etextno)
  File "C:\Python27\lib\site-packages\gutenberg\query\extractors.py", line 30, in get_metadata
    query = cls._metadata()[etext:cls.predicate():]
  File "C:\Python27\lib\site-packages\gutenberg\query\api.py", line 103, in _metadata
    cls.__metadata = load_metadata()
  File "C:\Python27\lib\site-packages\gutenberg\acquire\metadata.py", line 130, in load_metadata
    return _open_or_create_metadata_graph()
  File "C:\Python27\lib\site-packages\gutenberg\acquire\metadata.py", line 112, in _open_or_create_metadata_graph
    _METADATA_DATABASE_SINGLETON.open(_METADATA_CACHE, create=False)
  File "C:\Python27\lib\site-packages\rdflib\graph.py", line 376, in open
    return self.__store.open(configuration, create)
  File "C:\Python27\lib\site-packages\rdflib\plugins\sleepycat.py", line 89, in open
    db_env = self._init_db_environment(homeDir, create)
  File "C:\Python27\lib\site-packages\rdflib\plugins\sleepycat.py", line 75, in _init_db_environment
    db_env.open(homeDir, ENVFLAGS | db.DB_CREATE)
MemoryError: (12, 'Not enough space -- unable to allocate memory for mutex; resize mutex region')
>>> 
>>> get_metadata('author', 2701)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\gutenberg\query\api.py", line 34, in get_metadata
    metadata_values = MetadataExtractor.get(feature_name).get_metadata(etextno)
  File "C:\Python27\lib\site-packages\gutenberg\query\extractors.py", line 31, in get_metadata
    return frozenset(result.toPython() for result in query)
  File "C:\Python27\lib\site-packages\gutenberg\query\extractors.py", line 31, in <genexpr>
    return frozenset(result.toPython() for result in query)
  File "C:\Python27\lib\site-packages\rdflib\graph.py", line 634, in objects
    for s, p, o in self.triples((subject, predicate, None)):
  File "C:\Python27\lib\site-packages\rdflib\graph.py", line 421, in triples
    for _s, _o in p.eval(self, s, o):
  File "C:\Python27\lib\site-packages\rdflib\paths.py", line 227, in _eval_seq
    for s, o in evalPath(graph, (subj, paths[0], None)):
  File "C:\Python27\lib\site-packages\rdflib\paths.py", line 425, in <genexpr>
    return ((s, o) for s, p, o in graph.triples(t))
  File "C:\Python27\lib\site-packages\rdflib\graph.py", line 424, in triples
    for (s, p, o), cg in self.__store.triples((s, p, o), context=self):
  File "C:\Python27\lib\site-packages\rdflib\plugins\sleepycat.py", line 371, in triples
    assert self.__open, "The Store must be open."
AssertionError: The Store must be open.
>>>
```

Any ideas what's wrong?

**Comment by c-w** [comment]
Resolving in favor of #31.
