### ISSUE TITLE
Package on PyPi is missing requirements.pip

### ISSUE THREAD

**Issue by cpeel** [c-w/Gutenberg#36]
~~~
root@ol-dev:/openlibrary/Gutenberg# pip --no-cache-dir install gutenberg==0.4.1
Collecting gutenberg==0.4.1
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Gutenberg-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-3CKm7N/gutenberg/setup.py", line 19, in <module>
        install_requires=list(line.strip() for line in open('requirements.pip')))
    IOError: [Errno 2] No such file or directory: 'requirements.pip'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3CKm7N/gutenberg
~~~

A fresh download of this repo + `python setup.py sdist` shows that the file is correctly included in the .tar.gz, but the PyPi one is clearly missing it:
~~~
root@ol-dev:/tmp# wget https://pypi.python.org/packages/source/G/Gutenberg/Gutenberg-0.4.1.tar.gz
--2016-01-03 15:13:19--  https://pypi.python.org/packages/source/G/Gutenberg/Gutenberg-0.4.1.tar.gz
Resolving pypi.python.org (pypi.python.org)... 23.235.47.223
Connecting to pypi.python.org (pypi.python.org)|23.235.47.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9933 (9.7K) [application/octet-stream]
Saving to: 'Gutenberg-0.4.1.tar.gz'

100%[==========================================================>] 9,933       --.-K/s   in 0s

2016-01-03 15:13:19 (97.7 MB/s) - 'Gutenberg-0.4.1.tar.gz' saved [9933/9933]

root@ol-dev:/tmp# tar tvfz Gutenberg-0.4.1.tar.gz | grep requirements
root@ol-dev:/tmp#
~~~

**Comment by c-w** [comment]
Hi @cpeel. Thanks for getting in touch. I'll have a look into this soon.

**Comment by c-w** [comment]
The `MANIFEST.in` needs to contain `include requirements.pip`

**Comment by cpeel** [comment]
But MANIFEST.in is excluded in .gitignore and thus isn't tracked in the repo. So while I agree with the solution, it needs a commit to modify .gitignore and add MANIFEST.in.
