### ISSUE TITLE
nosetest failures: UnicodeDecodeError

### ISSUE THREAD

**Issue by ikarth** [c-w/Gutenberg#46]
Downloading the source and running nosetest, I get eight UnicodeDecodeError test failures.

````
======================================================================                                        
ERROR: test_load_metadata (tests.test_acquire.TestLoadMetadata)                                               
----------------------------------------------------------------------                                        
Traceback (most recent call last):                                                                            
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\tests\_util.py", line 41, in setUp                      
    self.cache.populate()                                                                                     
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\tests\_util.py", line 58, in populate                   
    data = u('\n').join(item.rdf() for item in self.sample_data_factory())                                    
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\tests\_util.py", line 58, in <genexpr>                  
    data = u('\n').join(item.rdf() for item in self.sample_data_factory())                                    
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\tests\_sample_metadata.py", line 83, in all             
    yield SampleMetaData.for_etextno(int(etextno))                                                            
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\tests\_sample_metadata.py", line 77, in for_etextno     
    metadata = _load_metadata(etextno)                                                                        
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\tests\_sample_metadata.py", line 93, in _load_metadata  
    return json.load(open(data_path))                                                                         
  File "c:\tools\anaconda3\envs\genmoenv\Lib\json\__init__.py", line 265, in load                             
    return loads(fp.read(),                                                                                   
  File "f:\isaac\dev\nanogenmo2016\projects\virtualenvgutenberg\lib\encodings\cp1252.py", line 23, in decode  
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]                                         
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 56: character maps to <undefined>      
````

(I also get import sqlalchemy errors, which I'm assuming are unrelated.)
````
======================================================================
ERROR: test_delete (tests.test_metadata_cache.TestSqlite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\tests\test_metadata_cache.py", line 111, in setUp
    self.cache = SqliteMetadataCache(self.local_storage)
  File "F:\Isaac\Dev\nanogenmo2016\projects\Gutenberg\gutenberg\acquire\metadata.py", line 205, in __init__
    store = plugin.get('SQLAlchemy', Store)(identifier=_DB_IDENTIFIER)
  File "f:\isaac\dev\nanogenmo2016\projects\virtualenvgutenberg\lib\site-packages\rdflib\plugin.py", line 104, in get
    return p.getClass()
  File "f:\isaac\dev\nanogenmo2016\projects\virtualenvgutenberg\lib\site-packages\rdflib\plugin.py", line 81, in getClass
    self._class = self.ep.load()
  File "f:\isaac\dev\nanogenmo2016\projects\virtualenvgutenberg\lib\site-packages\pkg_resources\__init__.py", line 2249, in load
    return self.resolve()
  File "f:\isaac\dev\nanogenmo2016\projects\virtualenvgutenberg\lib\site-packages\pkg_resources\__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "f:\isaac\dev\nanogenmo2016\projects\virtualenvgutenberg\lib\site-packages\rdflib_sqlalchemy\SQLAlchemy.py", line 6, in <module>
    from . import sqlalchemy
ImportError: cannot import name 'sqlalchemy'
````

**Comment by ikarth** [comment]
Further testing is required, but initial signs point to this being caused by trying to run the library with Python 3.5 instead of Python 2.7.

**Comment by ikarth** [comment]
Running the tests with Python 2.7:
````
λ nosetests
...............table kb_50034ba4e5_asserted_statements Doesn't exist
.table kb_50034ba4e5_asserted_statements Doesn't exist
...............
----------------------------------------------------------------------
Ran 31 tests in 90.397s

OK
````
Any future maintainers will likely want to pay attention to the differences in unicode handling between Python 2 and Python 3, and possibly use six to smooth over any issues. But otherwise test the package with Python 2 and it will pass the tests.

**Comment by MasterOdin** [comment]
It's also that you wouldn't want to leave the pick of encoding up to the user's system as it might be choosing something that's going to be invalid. In this case, in python 3 your system is using "Windows-1252" while in python 2 it's using something else (utf-8?) which causes the test to pass. The test passes fine on Travis-CI for python 3.5.

I think it'd make sense though to explicitly say what encoding to use when opening these texts as well as to use stuff like `from __future__ import unicode_literals` to ensure we're using unicode literals through the system
